# ----------- QUERYS (SELECT) -----------

SELECT_ARTICULOS_POR_ESTADO = """
    SELECT 
        pa.ID, 
        pa.TITULO, 
        pa.FECHA, 
        pa.URL, 
        pa.FUENTE, 
        pa.DESCRIPCION,
        mps.ETIQUETAS_IA, 
        mps.SENTIMIENTO, 
        mps.RATING, 
        mps.NIVEL_RIESGO,
        mps.INDICADOR_VIOLENCIA, 
        mps.EDAD_RECOMENDADA, 
        mps.EXECUTION_TIME,
        COALESCE(mps.IS_PROCESSED, 0) AS IS_PROCESSED,
        mps.MODEL_NAME
    FROM PROCESO.PROCESSED_ARTICLES pa
    LEFT JOIN PROCESO.MODEL_PROCESS_STATUS mps
        ON pa.ID = mps.ARTICLE_ID AND mps.MODEL_NAME = ?
    WHERE COALESCE(mps.IS_PROCESSED, 0) = ?
"""

EXISTE_STATUS = """
    SELECT COUNT(*)
    FROM PROCESO.MODEL_PROCESS_STATUS
    WHERE ARTICLE_ID = ? AND MODEL_NAME = ?
"""

# ----------- COMMANDS (INSERT/UPDATE) -----------

INSERT_ARTICULO = """
    INSERT INTO PROCESO.PROCESSED_ARTICLES (
        TITULO, FECHA, URL, FUENTE, DESCRIPCION
    )
    OUTPUT INSERTED.ID
    VALUES (?, ?, ?, ?, ?)
"""

INSERTAR_STATUS = """
    INSERT INTO PROCESO.MODEL_PROCESS_STATUS (ARTICLE_ID, MODEL_NAME, IS_PROCESSED)
    VALUES (?, ?, ?)
"""

UPDATE_ARTICULO_IA = """
    UPDATE PROCESO.MODEL_PROCESS_STATUS
    SET 
        ETIQUETAS_IA = ?, 
        SENTIMIENTO = ?, 
        RATING = ?, 
        NIVEL_RIESGO = ?, 
        INDICADOR_VIOLENCIA = ?, 
        EDAD_RECOMENDADA = ?, 
        EXECUTION_TIME = ?,
        IS_PROCESSED = 1
    WHERE ARTICLE_ID = ? AND MODEL_NAME = ?
"""

ACTUALIZAR_STATUS = """
    UPDATE PROCESO.MODEL_PROCESS_STATUS
    SET IS_PROCESSED = ?
    WHERE ARTICLE_ID = ? AND MODEL_NAME = ?
"""

INSERT_LOG = """
    INSERT INTO PROCESO.IA_RESPONSE_LOG (
        ARTICLE_ID,
        MODEL_NAME,
        PROMPT,
        RESPONSE,
        FILTERED_RESPONSE,
        STATUS_CODE,
        RESPONSE_TIME_SEC,
        TOKENS_USED,
        RESPONSE_DATE
    )
    OUTPUT INSERTED.ID
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
"""