CREATE SCHEMA JOURNAL;

CREATE TABLE JOURNAL.JOURNAL_ENTRY (
    ID INT PRIMARY KEY IDENTITY,         -- CLAVE PRIMARIA
    MODEL VARCHAR(100) NOT NULL,         -- NOMBRE DEL MODELO DE IA UTILIZADO
    CONTENT VARCHAR(MAX) NOT NULL,       -- CONTENIDO PROCESADO O GENERADO
    IS_PROCESSED BIT DEFAULT 0,          -- ¿YA FUE PROCESADO?
    EXECUTION_TIME DATETIME              -- TIEMPO DE EJECUCIÓN
)

